name: MLflow CI Training

# Trigger: Berjalan saat ada push ke branch master
on:
  push:
    branches:
      - master # <-- DIUBAH DARI 'main'

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout kode repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Setup Conda (termasuk Python 3.9)
    # Ini diperlukan karena MLProject Anda mereferensikan 'conda.yaml'
    - name: Set up Conda (termasuk Python 3.9)
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: '3.9'
        auto-activate-base: true # Penting agar 'conda' dikenali

    # 3. Install dependencies untuk runner (terutama MLflow client)
    # Step ini tetap diperlukan agar runner dapat menemukan perintah 'mlflow run'

    # 3.a Ensure conda shell functions are available in non-interactive bash
    - name: Initialize Conda for bash
      run: |
        eval "$(conda shell.bash hook)"

    # 4. Jalankan MLflow Project
    # Perintah ini sekarang akan berhasil:
    # - Membaca file 'MLProject'
    # - Melihat 'conda_env: conda.yaml'
    # - Menggunakan 'conda' (dari Step 2) untuk membuat env dari 'conda.yaml'
    # - Menjalankan 'command' (python modelling.py) di dalam env baru tersebut
    - name: Run MLflow Project
      run: mlflow run MLProject/
